@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.mattpenguin.metalus.container;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;