@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.mattpenguin.metalus.common;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;