@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.mattpenguin.metalus.tileentity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;